# Generated by Django 6.0.6 on 2026-06-20 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='hilol market')),
                ('phone', models.CharField(max_length=20, verbose_name='9036701550')),
                ('address', models.TextField(verbose_name='Vatsroy')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='BIOLIFE')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='5000')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='1000')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='BIOLIFE')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='water.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.product')),
            ],
        ),
    ]
